title: "alTRUE Ecological Economy"
email: "altruist@valto.ro"
description: >- # this means to ignore newlines until "baseurl:"
  ğŸ’ The sustainability-aware altruistic economy uses open-source technology with data privacy.
subtext: "Updates, tips & opinions from the maintainers of alTRUEco."
subtitle: _Bottom-up_ economy to solve _Scarcity_ | _F/LOSS_ **Toolkit** with **data privacy**
author: eapo

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
